(cl:defpackage dnb_msgs-srv
  (:use )
  (:export
   "GETPROGRAMSLIST"
   "<GETPROGRAMSLIST-REQUEST>"
   "GETPROGRAMSLIST-REQUEST"
   "<GETPROGRAMSLIST-RESPONSE>"
   "GETPROGRAMSLIST-RESPONSE"
   "RUNPROGRAMWITHARGUMENTS"
   "<RUNPROGRAMWITHARGUMENTS-REQUEST>"
   "RUNPROGRAMWITHARGUMENTS-REQUEST"
   "<RUNPROGRAMWITHARGUMENTS-RESPONSE>"
   "RUNPROGRAMWITHARGUMENTS-RESPONSE"
   "SETINT32"
   "<SETINT32-REQUEST>"
   "SETINT32-REQUEST"
   "<SETINT32-RESPONSE>"
   "SETINT32-RESPONSE"
   "SETSTRING"
   "<SETSTRING-REQUEST>"
   "SETSTRING-REQUEST"
   "<SETSTRING-RESPONSE>"
   "SETSTRING-RESPONSE"
  ))

